#!/usr/bin/env bash

set -u

OUT_ROOT="reports"
INCLUDE_NETWORK=0
INCLUDE_FAH_LOGS=0

usage() {
  cat <<'USAGE'
Usage: collect-hardware-profile.sh [options]

Options:
  --output-dir DIR       Write report directory under DIR instead of reports/
  --include-network     Include redacted network interface summary
  --include-fah-logs    Include redacted Folding@home service/log excerpts
  -h, --help            Show this help

This script is designed for public-safe evidence collection. It avoids dumping
environment variables and only collects F@H logs when explicitly requested.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output-dir)
      shift
      OUT_ROOT="${1:-reports}"
      ;;
    --include-network)
      INCLUDE_NETWORK=1
      ;;
    --include-fah-logs)
      INCLUDE_FAH_LOGS=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="${OUT_ROOT}/hardware-profile-${STAMP}"
mkdir -p "$OUT_DIR"

run_cmd() {
  local name="$1"
  shift
  {
    echo "$ $*"
    "$@"
    local code=$?
    echo
    echo "exit_code=${code}"
  } > "${OUT_DIR}/${name}.txt" 2>&1
}

run_shell() {
  local name="$1"
  shift
  {
    echo "$ $*"
    sh -c "$*"
    local code=$?
    echo
    echo "exit_code=${code}"
  } > "${OUT_DIR}/${name}.txt" 2>&1
}

copy_if_exists() {
  local src="$1"
  local dest="$2"
  if [ -f "$src" ]; then
    cp "$src" "${OUT_DIR}/${dest}"
  fi
}

redact_file() {
  local file="$1"
  [ -f "$file" ] || return 0
  if command -v perl >/dev/null 2>&1; then
    perl -0777 -pi -e 's/([Pp]asskey|[Tt]oken|[Ss]ecret|[Pp]assword|[Aa]pi[_ -]?[Kk]ey)(\s*[=:]\s*)\S+/$1$2[REDACTED]/g; s/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/[EMAIL_REDACTED]/g' "$file"
  fi
}

redact_tree() {
  find "$OUT_DIR" -type f -name "*.txt" -print | while read -r file; do
    redact_file "$file"
  done
}

cat > "${OUT_DIR}/README.md" <<EOF
# Hardware Profile ${STAMP}

Generated by \`scripts/collect-hardware-profile.sh\`.

Options:

- include_network: ${INCLUDE_NETWORK}
- include_fah_logs: ${INCLUDE_FAH_LOGS}

Review files before publishing. Redaction is best-effort.
EOF

run_cmd date-utc date -u
run_cmd uname uname -a
run_shell os-release 'cat /etc/os-release 2>/dev/null || sw_vers 2>/dev/null || true'
run_shell arch 'uname -m; command -v arch >/dev/null 2>&1 && arch || true'
run_shell cpu 'lscpu 2>/dev/null || sysctl -a machdep.cpu 2>/dev/null || true'
run_shell memory 'free -h 2>/dev/null || vm_stat 2>/dev/null || true'
run_shell disk 'df -h'

run_shell nvidia-smi-list 'nvidia-smi -L'
run_shell nvidia-smi-query 'nvidia-smi --query-gpu=name,uuid,pci.bus_id,driver_version,cuda_version,memory.total,power.limit --format=csv,noheader,nounits'
run_shell nvidia-smi-full 'nvidia-smi -q'
run_shell nvcc-version 'nvcc --version'
run_shell cuda-libraries 'ldconfig -p 2>/dev/null | grep -Ei "cuda|nvidia|OpenCL" || true'

run_shell opencl-info 'clinfo 2>/dev/null || true'
run_shell hip-info 'rocminfo 2>/dev/null || true'

run_shell pci-gpu-summary 'lspci -nn 2>/dev/null | grep -Ei "nvidia|vga|3d|display|cuda" || true'
run_shell pci-nvidia-detail 'lspci -vvnn -d 10de: 2>/dev/null || true'
run_shell kernel-modules 'lsmod 2>/dev/null | grep -Ei "nvidia|nouveau" || true'

run_shell tools 'for c in git cmake make gcc g++ clang clang++ python3 scons; do command -v "$c" >/dev/null 2>&1 && { echo "## $c"; "$c" --version 2>&1 | head -n 3; }; done'
run_shell fah-client-version 'fah-client --version 2>/dev/null || FAHClient --version 2>/dev/null || true'

if [ "$INCLUDE_NETWORK" -eq 1 ]; then
  run_shell network-brief 'ip -brief addr 2>/dev/null || ifconfig 2>/dev/null || true'
fi

if [ "$INCLUDE_FAH_LOGS" -eq 1 ]; then
  run_shell fah-service-status 'systemctl status --no-pager -l fah-client 2>/dev/null || service fah-client status 2>/dev/null || true'
  run_shell fah-journal-tail 'journalctl -u fah-client --no-pager -n 300 2>/dev/null || true'
  run_shell fah-log-tail 'for f in /var/log/fah-client/* /var/lib/fah-client/log.txt ./log.txt; do [ -f "$f" ] && { echo "## $f"; tail -n 300 "$f"; }; done'
fi

redact_tree

cat > "${OUT_DIR}/SUMMARY.md" <<EOF
# Summary

- Timestamp: ${STAMP}
- Output directory: ${OUT_DIR}
- Include network: ${INCLUDE_NETWORK}
- Include F@H logs: ${INCLUDE_FAH_LOGS}

## Files

EOF

find "$OUT_DIR" -maxdepth 1 -type f -name "*.txt" -print | sort | while read -r file; do
  printf -- "- %s\n" "$(basename "$file")" >> "${OUT_DIR}/SUMMARY.md"
done

echo "Wrote ${OUT_DIR}"
